### ISSUE TITLE
Getting error sol versions

### ISSUE THREAD

**Issue by balook** [unhackedctf/audius#2]
![Screenshot_1](https://user-images.githubusercontent.com/36122758/192014410-9fd6f466-a3b9-4705-9fec-194c6a60cf6b.png)

**Comment by zobront** [comment]
Manually go into lib/forge-std/src/Vm.sol and change the version to 0.5.0.

**Comment by balook** [comment]
![Uploading Screenshot_2.png…]()

**Comment by balook** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/36122758/192045492-0baccfd0-186b-4274-a671-8345f98fb07a.png)

**Comment by balook** [comment]
I changed to both 
pragma solidity ^0.5.0;

and 

pragma solidity 0.5.0;

**Comment by zobront** [comment]
Look in that list of errors. Anything that's >=0.6.0 (Script.sol, StdJson.sol), do the same thing or delete them.

**Comment by balook** [comment]
I changed the following files to ^0.5.0 and it worked 

lib/ds-test/src/test.sol (>=0.5.0)
    lib/forge-std/src/Vm.sol (>=0.6.0 <0.9.0)
    lib/forge-std/src/console.sol (>=0.4.22 <0.9.0)
    
    
    @zobront front next please provide .gitmodules too
