### ISSUE TITLE
Challenge source code does not have the vulnerability

### ISSUE THREAD

**Issue by captain-woof** [unhackedctf/audius#3]
Currently, after commit a16fa8d03cb7088de2cb6a3d92a8a311f5fdca6d, the challenge is not actually solvable, because of [this](https://github.com/unhackedctf/audius/commit/a16fa8d03cb7088de2cb6a3d92a8a311f5fdca6d#diff-a6a42143b98ffdb819d778430bc1d0daa8bfb6d16bc652e44d0d0c5e5f3b48f4).

As a suggestion, go back the commit history, then try solving this one.

I kept banging my head against the wall trying to find the storage collision as articles kept stating that it's supposed to be at slot #0, but I could clearly see that it was not.

Then I looked at the code. :-|

**Comment by zobront** [comment]
@captain-woof So sorry about that. I was playing around with some pieces locally before pushing the solutions and closing contest and must have accidentally pushed this too. Sorry if it wasted your time — it's fixed now.

**Comment by captain-woof** [comment]
@zobront Hey, no problem ser! Rabbit-holes are always fun (as long as there's an end).

Thanks for these challenges.
